---
output: html_document
editor_options: 
  chunk_output_type: console
---


## Theory of Mind / Empathy

### Yoni Task

```{r message=FALSE}
df %>% 
  group_by(Participant) %>% 
  select(starts_with("YONI_")) |> 
  summarise_all(mean, na.rm=TRUE) |> 
  tidyr::pivot_longer(-Participant, values_to = "Scores") |> 
  mutate(name = paste0(str_replace(name, "_", " ("), ")")) |> 
  ggplot(aes(x = Scores, fill = name)) +
  geom_density() +
  scale_fill_manual(values = c("YONI (Affective)" = "Purple",
                                 "YONI (Cognitive)" = "Blue",
                                 "YONI (Physical)" = "Green",
                                 "YONI (Total)"= "DarkBlue"),
                      guide = "none") +
  facet_wrap(~name, scales = "free")
```

### BES Questionnaire

```{r message=FALSE}
df %>% 
  group_by(Participant) %>% 
  select(starts_with("BES_")) |> 
  summarise_all(mean, na.rm=TRUE) |> 
  tidyr::pivot_longer(-Participant, values_to = "Scores") |> 
  mutate(name = paste0(str_replace(name, "_", " ("), ")")) |> 
  ggplot(aes(x = Scores, fill = name)) +
  geom_density() +
  scale_fill_manual(values = c("BES (Affective)" = "Purple",
                               "BES (Cognitive)" = "Blue",
                               "BES (Total)"= "DarkBlue"),
                      guide = "none") +
  facet_wrap(~name, scales = "free")
```

## Interoception

### Heartbeat Counting Task (HCT)

```{r message=FALSE}
df %>% 
  group_by(Participant) %>% 
  select(starts_with("HCT_")) |> 
  summarise_all(mean, na.rm=TRUE) |> 
  tidyr::pivot_longer(-Participant, values_to = "Scores") |> 
  mutate(name = paste0(str_replace(name, "_", " ("), ")")) |> 
  ggplot(aes(x = Scores, fill = name)) +
  geom_density() +
  scale_fill_manual(values = c("HCT (Accuracy)" = "Red",
                               "HCT (Awareness)" = "Orange",
                               "HCT (Confidence)"= "DarkOrange"),
                      guide = "none") +
  facet_wrap(~name, scales = "free")
```


### Heartbeat Tracking Task (HTT)


```{r message=FALSE}
htt_data <- read.csv("preprocessing/HTT_extracted.csv") |> 
  mutate(Condition = fct_recode(Condition, "NoGuessPerturbed" = "NoGuess_Perturbed")) |> 
  rename(Distance = Time_to_Rpeak) 

htt_data |>
  ggplot(aes(x = Distance, fill = Condition)) +
  geom_histogram(binwidth = 0.05, alpha = 0.5, position="identity") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  facet_wrap(~ID) +
  see::theme_modern() 
```


### MAIA

```{r message=FALSE}
df %>% 
  group_by(Participant) %>% 
  select(starts_with("MAIA_")) |> 
  summarise_all(mean, na.rm=TRUE) |> 
  tidyr::pivot_longer(-Participant, values_to = "Scores") |> 
  mutate(name = paste0(str_replace(name, "_", " ("), ")")) |> 
  ggplot(aes(x = Scores, fill = name)) +
  geom_density() +
  scale_fill_brewer(palette = "Reds", guide = "none") +
  facet_wrap(~name, scales = "free")
```


## Deception

### LIE Scale

```{r message=FALSE}
df %>% 
  group_by(Participant) %>% 
  select(starts_with("LIE_")) |> 
  summarise_all(mean, na.rm=TRUE) |> 
  tidyr::pivot_longer(-Participant, values_to = "Scores") |> 
  mutate(name = paste0(str_replace(name, "_", " ("), ")")) |> 
  ggplot(aes(x = Scores, fill = name)) +
  geom_density() +
  scale_fill_manual(values = c("LIE (Ability)" = "#2196F3",
                               "LIE (Frequency)" = "#4CAF50",
                               "LIE (Contextuality)"= "#FF9800",
                               "LIE (Negativity)"= "#E91E63"),
                    guide = "none") +
  facet_wrap(~name, scales = "free")
```

### Deception Task

#### Physiological Processing

```{r warning=FALSE}
df_physio <- read.csv("data/data_physio_DeceptionTask.csv") |> 
  dplyr::filter(ID != 30) |> 
  tidyr::pivot_longer(starts_with("X"), names_to = "Time", values_to = "HeartRate") |> 
  mutate(Time = as.numeric(str_remove(Time, "X"))-500,
         group = paste0(ID, condition, instruction),
         condition = fct_recode(condition, "Interrogation" = "Social"),
         instruction = fct_relevel(instruction, "TRUTH")) |> 
  group_by(condition, instruction, Time) |> 
  summarise(HeartRate = mean(HeartRate)) |> 
  ungroup()
  
df_physio |> 
  ggplot(aes(x = Time, y = HeartRate)) +
  annotate("rect", xmin=1500, xmax=2500, ymin=-Inf, ymax=Inf, alpha=0.1, fill = "green") +
  geom_line(aes(color = condition, linetype = instruction), size=1) +
  geom_vline(aes(xintercept=0), linetype = "dotted") +
  labs(y = "Average Heart Rate (bpm)", x = "Time (ms)") +
  scale_color_manual(values = c("Polygraph" = "#FF5722", "Interrogation" = "#2196F3")) +
  theme(legend.position = "top", legend.title=element_blank())
```

#### Summary Table

```{r warning=FALSE}
df |> 
  group_by(Participant, Answer) |> 
  summarise(Confidence = paste(insight::format_value(mean(Confidence, na.rm = TRUE)),
                               " +- ",
                               insight::format_value(sd(Confidence, na.rm = TRUE))),
            RT = paste(insight::format_value(mean(RT, na.rm = TRUE)),
                       " +- ",
                       insight::format_value(sd(RT, na.rm = TRUE)))) |> 
  arrange(Participant) |> 
  knitr::kable()
```

#### Outliers

##### Participants

```{r warning=FALSE}
df |> 
  select(Participant, Confidence, RT, HeartRate) |> 
  tidyr::pivot_longer(-Participant) |> 
  ggplot(aes(x=Participant, y=value)) +
  geom_violin(aes(fill=name), color="white", alpha=0.5) +
  geom_jitter(aes(color=name), width = 0.25, height=0, shape="+", size=2) +
  facet_wrap(~name, scales="free", nrow=3) +
  guides(fill="none", color="none")

df$Confidence[df$Participant %in% c("S9", "S29")] <- NA # Extreme responses
sum(is.na(df$Confidence)) / nrow(df) * 100
df$HeartRate[df$Participant == "S30"] <- NA # Extreme values
sum(is.na(df$HeartRate)) / nrow(df) * 100
df$RT[df$Participant == "S13"] <- NA # Slower than the others
df$RT[df$RT > 8.25] <- NA # Extreme RT values 
sum(is.na(df$RT)) / nrow(df) * 100
```

##### Observations

```{r warning=FALSE}
df <- df |> 
  # Remove participants
  group_by(Participant) |> 
  mutate(Outliers_RT = as.logical(performance::check_outliers(RT, method = "zscore", threshold = qnorm(0.9999))),
         Outliers_Physio = as.logical(performance::check_outliers(HeartRate, method = "zscore", threshold = qnorm(0.9999)))) |> 
  ungroup()
```

```{r warning=FALSE}
df |> 
  group_by(Participant) |> 
  summarise(Physio = sum(Outliers_RT) / n(),
            RT = sum(Outliers_Physio) / n()) |> 
  tidyr::pivot_longer(-Participant, names_to = "Outlier_Type") |> 
  ggplot(aes(x=Participant, y = value, fill = Outlier_Type)) +
  geom_bar(stat = "identity") + 
  scale_y_continuous(labels = scales::percent) + 
  labs(y = "Percentage of trials") +
  ggtitle("Number of Trial Dropped Per Participant")
  
df$RT[df$Outliers_RT] <- NA
df$HeartRate[df$Outliers_Physio] <- NA
```


#### Distributions

```{r warning=FALSE, fig.height=figheight*2}
p1 <- df |> 
  ggplot(aes(x = Confidence, fill = Participant)) +
  geom_density(alpha = 0.1) +
  see::scale_fill_material_d(palette = "rainbow", guide = "none") +
  scale_x_continuous(labels = scales::percent, expand=expansion(c(0, .05))) +
  scale_y_continuous(expand=expansion(c(0, .05))) +
  facet_wrap(~Answer)
p2 <- df |> 
  ggplot(aes(x = RT, fill = Participant)) +
  geom_density(alpha = 0.1) +
  see::scale_fill_material_d(palette = "rainbow", guide = "none") +
  scale_x_continuous(expand=expansion(c(0, .05))) +
  scale_y_continuous(expand=expansion(c(0, .05))) +
  facet_wrap(~Answer)
p3 <- df |> 
  ggplot(aes(x = HeartRate, fill = Participant)) +
  geom_density(alpha = 0.1) +
  see::scale_fill_material_d(palette = "rainbow", guide = "none") +
  scale_x_continuous(expand=expansion(c(0, .05))) +
  scale_y_continuous(expand=expansion(c(0, .05))) +
  facet_wrap(~Answer)
p1 / p2 / p3
```

