---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
plot_effect <- function(model, var) {
  viz_data <- estimate_relation(model, at = c("condition", var, "instruction"))
  ggplot(data = viz_data, aes_string(x = var, y = "Predicted")) +
    geom_point(data = df.plot, aes_string(y = "DT_confidence", color = "condition"), show.legend = FALSE) +
    geom_line(aes_string(color = "condition")) +
    geom_ribbon(aes_string(ymin = "CI_low", ymax = "CI_high", fill = "condition"), alpha = 0.3) + 
    facet_wrap(~instruction)
}
plot_effect(model, "MAIA_total")
```

## The effect of TOM ability on confidence and RT
### Yoni task
```{r}
model <- glmmTMB(DT_confidence ~ instruction/(condition*yoni_total) + (1|ID) + (1|item), data = df)
parameters(model, effects = "fixed")
viz_data <- estimate_relation(model, at = c("condition", "yoni_total", "instruction"))
ggplot(data = viz_data, aes(x = yoni_total, y = Predicted)) +
  geom_point(data = df.plot, aes(y = DT_confidence, color = condition), show.legend = FALSE) +
  geom_line(aes(color = condition)) +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high, fill = condition), alpha = 0.3) + 
  facet_wrap(~instruction)
```
the higher someone scores in yoni, the bigger the difference in lie and truth

### BES
```{r}
model <- glmmTMB(DT_confidence ~ instruction/(condition*BES_total) + (1|ID) + (1|item), data = df)
parameters(model, effects = "fixed")
viz_data <- estimate_relation(model, at = c("condition", "BES_total", "instruction"))
ggplot(data = viz_data, aes(x = BES_total, y = Predicted)) +
  geom_point(data = df.plot, aes(y = DT_confidence, color = condition), show.legend = FALSE) +
  geom_line(aes(color = condition)) +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high, fill = condition), alpha = 0.3) + 
  facet_wrap(~instruction)
```

## The effect of interoceptive ability on confidence and RT
### HCT
```{r}
model <- glmmTMB(DT_confidence ~ instruction/(condition*HCT_accuracy) + (1|ID) + (1|item), data = df)
parameters(model, effects = "fixed")
viz_data <- estimate_relation(model, at = c("condition", "HCT_accuracy", "instruction"))
ggplot(data = viz_data, aes(x = HCT_accuracy, y = Predicted)) +
  geom_point(data = df.plot, aes(y = DT_confidence, color = condition), show.legend = FALSE) +
  geom_line(aes(color = condition)) +
  geom_ribbon(aes(ymin = CI_low, ymax = CI_high, fill = condition), alpha = 0.3) + 
  facet_wrap(~instruction)
```

### MAIA
```{r}
model <- glmmTMB(DT_confidence ~ instruction/(condition*MAIA_total) + (1|ID) + (1|item), data = df)
parameters(model, effects = "fixed")
parameters(emmeans::emtrends(model, ~instruction, var = "MAIA_total")) # main effect only significant for lie, averages (properly) over condition -> similar to instruction/MAIA_total but takes into account condition
```