---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Yoni Task {.tabset}

- Confidence: effect in total, cognitive and physical.
- RT: effect in cognitive only.
- Heart rate: no effect.


### Confidence

```{r message=FALSE, warning=FALSE}
results <- data.frame()
for (var in c("YONI_Total", "YONI_Cognitive", "YONI_Affective", "YONI_Physical")) {
  model <- glmmTMB(as.formula(paste0("Confidence ~ Answer / (Condition / ", 
                                     var, 
                                     ") + (1|Participant) + (1|Item)")), 
                   data = df, 
                   family = beta_family())
  
  results <- parameters::parameters(model, effects = "fixed", keep=var) |> 
    mutate(Parameter = str_remove(Parameter, "Answer|Condition")) |> 
    separate(Parameter, sep=":", into = c("Answer", "Condition", "Variable")) |> 
    data_relocate(select="Variable", before=1) |> 
    rbind(results)
}

display(results, stars=TRUE)
```

### RT


```{r message=FALSE, warning=FALSE}
results <- data.frame()
for (var in c("YONI_Total", "YONI_Cognitive", "YONI_Affective", "YONI_Physical")) {
  model <- glmmTMB(as.formula(paste0("RT ~ Answer / (Condition / ", 
                                     var, 
                                     ") + (1|Participant) + (1|Item)")), 
                   data = df)
  
  results <- parameters::parameters(model, effects = "fixed", keep=var) |> 
    mutate(Parameter = str_remove(Parameter, "Answer|Condition")) |> 
    separate(Parameter, sep=":", into = c("Answer", "Condition", "Variable")) |> 
    data_relocate(select="Variable", before=1) |> 
    rbind(results)
}

display(results, stars=TRUE)
```


### Heart Rate

```{r message=FALSE, warning=FALSE}
results <- data.frame()
for (var in c("YONI_Total", "YONI_Cognitive", "YONI_Affective", "YONI_Physical")) {
  model <- glmmTMB(as.formula(paste0("HeartRate ~ Answer / (Condition / ", 
                                     var, 
                                     ") + (1|Participant) + (1|Item)")), 
                   data = df)
  
  results <- parameters::parameters(model, effects = "fixed", keep=var) |> 
    mutate(Parameter = str_remove(Parameter, "Answer|Condition")) |> 
    separate(Parameter, sep=":", into = c("Answer", "Condition", "Variable")) |> 
    data_relocate(select="Variable", before=1) |> 
    rbind(results)
}

display(results, stars=TRUE)
```




### Correlation with LIE Scale

```{r message=FALSE, warning=FALSE}
dfsub <- df |> 
  select(Participant, 
         starts_with("LIE_"), 
         starts_with("YONI_")) |> 
  group_by(Participant) |> 
  summarise_all(mean)

correlation(select(dfsub, starts_with("LIE_")), select(dfsub, starts_with("YONI_")), p_adjust = "none")
```



## BES {.tabset}

- Confidence: effect in all.
- RT: no effect.
- Heart rate: effect in all.

### Confidence

```{r message=FALSE, warning=FALSE}
results <- data.frame()
for (var in c("BES_Total", "BES_Cognitive", "BES_Affective")) {
  model <- glmmTMB(as.formula(paste0("Confidence ~ Answer / (Condition / ", 
                                     var, 
                                     ") + (1|Participant) + (1|Item)")), 
                   data = df, 
                   family = beta_family())
  
  results <- parameters::parameters(model, effects = "fixed", keep=var) |> 
    mutate(Parameter = str_remove(Parameter, "Answer|Condition")) |> 
    separate(Parameter, sep=":", into = c("Answer", "Condition", "Variable")) |> 
    data_relocate(select="Variable", before=1) |> 
    rbind(results)
}

display(results, stars=TRUE)
```

### RT


```{r message=FALSE, warning=FALSE}
results <- data.frame()
for (var in c("BES_Total", "BES_Cognitive", "BES_Affective")) {
  model <- glmmTMB(as.formula(paste0("RT ~ Answer / (Condition / ", 
                                     var, 
                                     ") + (1|Participant) + (1|Item)")), 
                   data = df)
  
  results <- parameters::parameters(model, effects = "fixed", keep=var) |> 
    mutate(Parameter = str_remove(Parameter, "Answer|Condition")) |> 
    separate(Parameter, sep=":", into = c("Answer", "Condition", "Variable")) |> 
    data_relocate(select="Variable", before=1) |> 
    rbind(results)
}

display(results, stars=TRUE)
```


### Heart Rate

```{r message=FALSE, warning=FALSE}
results <- data.frame()
for (var in c("BES_Total", "BES_Cognitive", "BES_Affective")) {
  model <- glmmTMB(as.formula(paste0("HeartRate ~ Answer / (Condition / ", 
                                     var, 
                                     ") + (1|Participant) + (1|Item)")), 
                   data = df)
  
  results <- parameters::parameters(model, effects = "fixed", keep=var) |> 
    mutate(Parameter = str_remove(Parameter, "Answer|Condition")) |> 
    separate(Parameter, sep=":", into = c("Answer", "Condition", "Variable")) |> 
    data_relocate(select="Variable", before=1) |> 
    rbind(results)
}

display(results, stars=TRUE)
```




### Correlation with LIE Scale

```{r message=FALSE, warning=FALSE}
dfsub <- df |> 
  select(Participant, 
         starts_with("LIE_"), 
         starts_with("BES_")) |> 
  group_by(Participant) |> 
  summarise_all(mean)

correlation(select(dfsub, starts_with("LIE_")), select(dfsub, starts_with("BES_")), p_adjust = "none")
```
