```{r clear everything}
rm(list=ls())
cat("\014")
```


```{r load packages}
library(tidyverse)
```

```{r demo}
rm(list=ls())
cat("\014")

mydata <- read.csv('../../data/data_questionnaire/Demographics.csv', stringsAsFactors = FALSE)[-c(1:2), -c(1:17, 30, 32, 34, 36)] 

mydata <- mydata %>% 
  rename(Name = Q2,
         ID = Q3,
         Matric = Q4,
         HP = Q5,
         Email = Q6,
         Gender = Q7,
         Age = Q8,
         Birthday = Q9,
         Handedness = Q10,
         School = Q11,
         Course = Q12,
         Polyjc = Q13,
         Ethnicity = Q14,
         Religion = Q15,
         Nationality = Q16,
         RaisedinSG = Q17,
         LivedinSG = Q18) %>% 
  mutate(ID = as.numeric(ID)) %>% 
  arrange(ID)

write.csv(mydata, file = "demo.csv", row.names = FALSE)
```

```{r tom obj yoni}
rm(list=ls())
cat("\014")

mydata <- data.frame()
for (participant in list.files("../../data/data_experimental")) {
  df_sub <- read.csv(paste0("../../data/data_experimental/", participant, "/yoni/", participant, "_untitled.csv"))[-c(1:3,28,61,104), -c(4,5,7:38,42:47)]
  mydata <- rbind(mydata, df_sub)
}

data <- mydata %>% 
  rename(response = mouse_2.clicked_name,
         responseRT = mouse_2.time,
         ID = participant) %>% 
  mutate(answer = ifelse(correct == response, 1, 0)) %>% 
  select(ID, everything()) #move ID column to front

results <- data %>%
  group_by(ID, condition) %>%
  summarise(total = sum(answer)) %>%
  pivot_wider(names_from = condition, values_from = total) %>%
  mutate(yoni_total = affect+cognitive+physical) %>%
  rename(yoni_affective = affect,
         yoni_cognitive = cognitive,
         yoni_physical = physical)

write.csv(data, file = "yoni_extracted.csv", row.names=FALSE)
write.csv(results, file = "yoni_processed.csv", row.names=FALSE)
```

```{r tom subj bes}
rm(list=ls())
cat("\014")

mydata <- read.csv("../../data/data_questionnaire/BES.csv", stringsAsFactors = FALSE)[-c(1, 2), -c(1:17)] 

results <- mydata %>% 
  rename(Q1 = Q3_1,
       Q2 = Q3_2,
       Q3 = Q3_3,
       Q4 = Q3_4,
       Q5 = Q3_5,
       Q6 = Q3_6,
       Q7 = Q3_7,
       Q8 = Q3_8,
       Q9 = Q3_9,
       Q10 = Q3_10,
       Q11 = Q3_11,
       Q12 = Q3_12,
       Q13 = Q3_13,
       Q14 = Q3_14,
       Q15 = Q3_15,
       Q16 = Q3_16,
       Q17 = Q3_17,
       Q18 = Q3_18,
       Q19 = Q3_19,
       Q20 = Q3_20,
       ID = Q2) %>%
  
  mutate(Q1 = recode(Q1, "1" = "5", "2" = "4", "4" = "2", "5" = "1"),
    Q6 = recode(Q6, "1" = "5", "2" = "4", "4" = "2", "5" = "1"),
    Q7 = recode(Q7, "1" = "5", "2" = "4", "4" = "2", "5" = "1"),
    Q8 = recode(Q8, "1" = "5", "2" = "4", "4" = "2", "5" = "1"),
    Q13 = recode(Q13, "1" = "5", "2" = "4", "4" = "2", "5" = "1"),
    Q18 = recode(Q18, "1" = "5", "2" = "4", "4" = "2", "5" = "1"),
    Q19 = recode(Q19, "1" = "5", "2" = "4", "4" = "2", "5" = "1"),
    Q20 = recode(Q20, "1" = "5", "2" = "4", "4" = "2", "5" = "1")) %>% 
  
  mutate(Q1 = as.numeric(Q1), Q2 = as.numeric(Q2), Q3 = as.numeric(Q3), Q4 = as.numeric(Q4), 
         Q5 = as.numeric(Q5), Q6 = as.numeric(Q6), Q7 = as.numeric(Q7), Q8 = as.numeric(Q8), 
         Q9 = as.numeric(Q9), Q10 = as.numeric(Q10), Q11 = as.numeric(Q11), Q12 = as.numeric(Q12), 
         Q13 = as.numeric(Q13), Q14 = as.numeric(Q14), Q15 = as.numeric(Q15), Q16 = as.numeric(Q16),
         Q17 = as.numeric(Q17), Q18 = as.numeric(Q18), Q19 = as.numeric(Q19), Q20 = as.numeric(Q20)) %>%
  
  mutate(BES_cognitive = Q3+Q6+Q9+Q10+Q12+Q14+Q16+Q19+Q20) %>% 
  mutate(BES_affective = Q1+Q2+Q4+Q5+Q7+Q8+Q11+Q13+Q15+Q17+Q18) %>% 
  mutate(BES_total = BES_cognitive+BES_affective) %>% 
  
  arrange(ID)

write.csv(results, file = "BES_processed.csv", row.names=FALSE)
```

```{r int obj heartbeat}
rm(list=ls())
cat("\014")

mydata <- data.frame()
for (participant in list.files("../../data/data_experimental")) {
  df_sub <- read.csv(paste0("../../data/data_experimental/", participant, "/heartbeat/", participant, "_heartbeat.csv"))[-c(6:9), -c(1, 3:8, 12:31, 33:38)]  
  mydata <- rbind(mydata, df_sub)
}

data <- mydata %>% 
  rename(hbcount_reported = heartbeatresponse.text,
       HCT_confidence = confidenceslider.response,
       HCT_confidenceRT = confidenceslider.rt,
       ID = participant) %>% 
  
  select(ID, everything()) %>% #move ID column to front
  
  mutate(hbcount_reported = str_remove_all(hbcount_reported, "Enter Number")) %>% 
  mutate(hbcount_reported = as.numeric(hbcount_reported)) %>% 
  mutate(HCT_confidence = as.numeric(HCT_confidence)) %>% 
  
  arrange(ID, time)

HCT <- read.csv("../heartbeat/HCT.csv", stringsAsFactors = FALSE)[-c(2,8:10)] %>% 
  rename(participant = Participant.number) %>%
  pivot_longer(!participant, names_to = "task", values_to = "hbcount_real")
data <- cbind(data, HCT)

data <- data %>% 
  select(-c(participant, task)) %>% 
  mutate(numerator = hbcount_real - hbcount_reported) %>% 
  mutate(numerator = abs(numerator)) %>% 
  mutate(denominator = (hbcount_real + hbcount_reported)/2) %>% 
  mutate(HCT_accuracy = 1 - numerator/denominator)

df_awareness <- data.frame()
for(participant in unique(data$ID)) {
  conf <- data[data$ID == participant, "HCT_confidence"]
  acc <- data[data$ID == participant, "HCT_accuracy"]
  awa <- cor(conf, acc, use = "pairwise.complete.obs")
  df_awareness <- rbind(df_awareness,
                       data.frame(ID = participant,
                                  HCT_awareness = awa))
}

data <- merge(data, df_awareness, by = "ID")
results <- data %>% 
  select(c(ID, HCT_confidence, HCT_accuracy, HCT_awareness)) %>% 
  group_by(ID) %>%
  summarise_all(mean, na.rm = TRUE)

parttwo <- data.frame()
for (participant in list.files("../../data/data_experimental")) {
  df_sub <- read.csv(paste0("../../data/data_experimental/", participant, "/heartbeat/", participant, "_heartbeat.csv"))[-c(1:5, 9), -c(1:13, 16:19, 22:25, 28:31, 33:38)]  
  parttwo <- rbind(parttwo, df_sub)
}
  
parttwo <- parttwo %>% 
  rename(guess = key_guess.keys,
         guessRT = key_guess.rt,
         noguess = key_noguess.keys,
         noguessRT = key_noguess.rt,
         onebreath = key_noguess_perturbed.keys,
         onebreathRT = key_noguess_perturbed.rt,
         ID = participant) %>% 
  group_by(ID) %>% 
  summarise_all(funs(trimws(paste(., collapse = ''))))

parttwo <- parttwo %>% 
  mutate(HCT_guess = str_count(parttwo$guess, "space")) %>% 
  mutate(HCT_noguess = str_count(parttwo$noguess, "space")) %>% 
  mutate(HCT_onebreath = str_count(parttwo$onebreath, "space")) %>% 
  select(c(ID, HCT_guess, HCT_noguess, HCT_onebreath))

results <- left_join(results, parttwo)

write.csv(data, file = "HCT_extracted.csv", row.names=FALSE)
write.csv(results, file = "HCT_processed.csv", row.names=FALSE)
```

```{r int subj maia2}
rm(list=ls())
cat("\014")

mydata <- read.csv('../../data/data_questionnaire/MAIA2.csv', stringsAsFactors = FALSE)[-c(1, 2), -c(1:17)] 

results <- mydata %>% 
  rename(Q1 = Q3_1,
       Q2 = Q3_2,
       Q3 = Q3_3,
       Q4 = Q3_4,
       Q5 = Q3_5,
       Q6 = Q3_6,
       Q7 = Q3_7,
       Q8 = Q3_8,
       Q9 = Q3_9,
       Q10 = Q3_10,
       Q11 = Q3_11,
       Q12 = Q3_12,
       Q13 = Q3_13,
       Q14 = Q3_14,
       Q15 = Q3_15,
       Q16 = Q3_16,
       Q17 = Q3_17,
       Q18 = Q3_18,
       Q19 = Q3_19,
       Q20 = Q3_20,
       Q21 = Q4_1,
       Q22 = Q4_2,
       Q23 = Q4_3,
       Q24 = Q4_4,
       Q25 = Q4_5,
       Q26 = Q4_6,
       Q27 = Q4_7,
       Q28 = Q4_8,
       Q29 = Q4_9,
       Q30 = Q4_10,
       Q31 = Q4_11,
       Q32 = Q4_12,
       Q33 = Q4_13,
       Q34 = Q4_14,
       Q35 = Q4_15,
       Q36 = Q4_16,
       Q37 = Q4_17,
       ID = Q2) %>% 
  
  mutate(Q5 = recode(Q5, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q6 = recode(Q6, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q7 = recode(Q7, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q8 = recode(Q8, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q9 = recode(Q9, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q10 = recode(Q10, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q11 = recode(Q11, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q12 = recode(Q12, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0"),
    Q15 = recode(Q15, "0" = "5", "1" = "4", "2" = "3", "3" = "2", "4" = "1", "5" = "0")) %>% 
  
  mutate(Q1 = as.numeric(Q1), Q2 = as.numeric(Q2), Q3 = as.numeric(Q3), Q4 = as.numeric(Q4),
         Q5 = as.numeric(Q5), Q6 = as.numeric(Q6), Q7 = as.numeric(Q7), Q8 = as.numeric(Q8),
         Q9 = as.numeric(Q9), Q10 = as.numeric(Q10), Q11 = as.numeric(Q11), Q12 = as.numeric(Q12),
         Q13 = as.numeric(Q13), Q14 = as.numeric(Q14), Q15 = as.numeric(Q15), Q16 = as.numeric(Q16),
         Q17 = as.numeric(Q17), Q18 = as.numeric(Q18), Q19 = as.numeric(Q19), Q20 = as.numeric(Q20),
         Q21 = as.numeric(Q21), Q22 = as.numeric(Q22), Q23 = as.numeric(Q23), Q24 = as.numeric(Q24),
         Q25 = as.numeric(Q25), Q26 = as.numeric(Q26), Q27 = as.numeric(Q27), Q28 = as.numeric(Q28),
         Q29 = as.numeric(Q29), Q30 = as.numeric(Q30), Q31 = as.numeric(Q31), Q32 = as.numeric(Q32),
         Q33 = as.numeric(Q33), Q34 = as.numeric(Q34), Q35 = as.numeric(Q35), Q36 = as.numeric(Q36),
         Q37 = as.numeric(Q37)) %>% 
  
  mutate(MAIA1 = (Q1+Q2+Q3+Q4)/4, MAIA2 = (Q5+Q6+Q7+Q8+Q9+Q10)/6, MAIA3 = (Q11+Q12+Q13+Q14+Q15)/5, MAIA4 = (Q16+Q17+Q18+Q19+Q20+Q21+Q22)/7,
        MAIA5 = (Q23+Q24+Q25+Q26+Q27)/5, MAIA6 = (Q28+Q29+Q30+Q31)/4, MAIA7 = (Q32+Q33+Q34)/3, MAIA8 = (Q35+Q36+Q37)/3) %>% 
  mutate(MAIA_total = (MAIA1+MAIA2+MAIA3+MAIA4+MAIA5+MAIA6+MAIA7+MAIA8)/8) %>%
  
  arrange(ID)

write.csv(results, file = "MAIA2_processed.csv", row.names=FALSE)
```

```{r deception subj}
rm(list=ls())
cat("\014")

mydata <- data.frame()
for (participant in list.files("../../data/data_experimental")) {
  df_sub <- read.csv(paste0("../../data/data_experimental/", participant, "/deception/", participant, "_deceptiontask.csv"), header = FALSE)[-c(1:11), -c(5:34, 37:46, 48:54)] %>% 
    mutate(trial = c(1:80)) %>% 
    mutate(condition = c(rep("Social", 40), rep("Polygraph", 40)))
  mydata <- rbind(mydata, df_sub)
}

inclusion <- read.csv("../final_processing/Errors.csv") %>%
  rename(ID = ï..participant,
         trial = Trial,
         inclusion = Inclusion,
         inclusion2 = Inclusion2)

data <- mydata %>% 
  rename(item = V1,
       style = V2,
       instruction = V3,
       question = V4,
       DT_confidence = V35,
       DT_confidenceRT = V36,
       ID = V47) %>% 
  
  mutate(DT_confidence = as.numeric(DT_confidence)) %>% 
  mutate(DT_confidenceRT = as.numeric(DT_confidenceRT)) %>% 
  mutate(instruction = as.factor(instruction)) %>% 
  mutate(ID = as.numeric(ID)) %>% 
  left_join(inclusion) %>% 
  
  select(ID, trial, condition, inclusion, inclusion2, everything()) #move columns to front

results <- data %>% 
  group_by(ID, instruction, style) %>% 
  summarise(DT_confidence_avg = mean(DT_confidence), DT_confidenceRT_avg = mean(DT_confidenceRT))

write.csv(data, file = "deceptiontask_extracted.csv", row.names=FALSE)
write.csv(results, file = "deceptiontask_processed.csv", row.names=FALSE)
```

```{r combine data}
data_combined <- read.csv("deceptiontask_extracted.csv") %>% 
  left_join(read.csv("deceptiontask_processed.csv")) %>% 
  left_join(read.csv("yoni_processed.csv")) %>% 
  left_join(read.csv("BES_processed.csv")) %>% 
  select(-c(contains("Q"))) %>% 
  left_join(read.csv("HCT_processed.csv")) %>% 
  left_join(read.csv("MAIA2_processed.csv")) %>% 
  select(-c(contains("Q"))) %>% 
  left_join(read.csv("demo.csv")) %>% 
  select(-c(Name, Matric, HP, Email, Birthday, School, Course, LivedinSG))

write.csv(data_combined, file = "../../data/data_combined.csv", row.names = FALSE)
```

