---
title: '**The Role of Interoception and Theory of Mind in Deception**'
shorttitle        : "TITLE"
author:
  - name          : "Dominique Makowski"
    affiliation   : " 1, *"
    address       : "HSS 04-18, 48 Nanyang Avenue, Singapore"
    email         : "dmakowski@ntu.edu.sg"
  - name          : "Zen J. Lau"
    affiliation   : " 1"
  - name          : "Tam Pham"
    affiliation   : " 1"
  - name          : "S.H. Annabel Chen"
    affiliation   : " 1, 2, 3, 4"
    corresponding : yes    # Define only one corresponding author
    address       : "HSS 04-19, 48 Nanyang Avenue, Singapore"
    email         : "annabelchen@ntu.edu.sg"
affiliation:
  - id            : "1"
    institution   : "School of Social Sciences, Nanyang Technological University, Singapore"
  - id            : "2"
    institution   : "Centre for Research and Development in Learning, Nanyang Technological University, Singapore"
  - id            : "3"
    institution   : "Lee Kong Chian School of Medicine, Nanyang Technological University, Singapore"
  - id            : "4"
    institution   : "National Institute of Education, Nanyang Technological University, Singapore"
abstract: |
output:
  papaja::apa6_word:
    keep_tex: yes
  pdf_document: default
  papaja::apa6_pdf:
    keep_tex: yes
keywords: ""
wordcount: ''
bibliography: ["references.bib"]
floatsintext: yes
figsintext: yes
figurelist: no
tablelist: no
footnotelist: no
linenumbers: yes
mask: no
draft: no
documentclass: apa6
classoption: man
header-includes:
- \usepackage[labelfont=bf, font={color=gray,small}]{caption}
- \usepackage{float}
- \usepackage[document]{ragged2e}
csl: utils/apa.csl
---

\justify

```{r r_setup, include = FALSE, warning=FALSE, message=FALSE}
library("papaja")
library("kableExtra")
options(knitr.kable.NA = 'None')
```

```{=html}
<!-- 
Journals:
Neuroscience Letters https://www.journals.elsevier.com/neuroscience-letters
Biological Psychology https://www.journals.elsevier.com/biological-psychology
Psychophysiology https://onlinelibrary.wiley.com/journal/14698986
Cognitive Neurodynamics https://www.springer.com/journal/11571
Neuroscience & Biobehavioral Reviews https://www.journals.elsevier.com/neuroscience-and-biobehavioral-reviews
-->
```
# Introduction

# Methods

## Participants

## Procedure

### 

## Measures

### 

## EEG Complexity Measures

## Data Analysis

# Results

# Discussion

# Funding

# Author Contributions

# Conflict of Interest Statement

# Acknowledgements

\newpage

# References

```{r create_r-references}
r_refs(file = "references.bib")
```

```{=tex}
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
```
::: {#refs}
:::

```{=tex}
\endgroup
```
